# Generated by Django 5.2.5 on 2025-10-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_cliente_bairro_cliente_mae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mae',
        ),
    ]
