# Generated by Django 4.2.2 on 2025-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0003_remove_cliente_bairro_remove_cliente_mae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariocustomizado",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
