# Generated by Django 5.2.5 on 2025-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="cliente",
            name="mae",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
