# Generated by Django 4.2.2 on 2025-11-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0004_alter_usuariocustomizado_cpf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
